In [16]:
import numpy as np
import time

In [3]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
size=1000000
py_list=list(range(size))
start=time.time()
py_list=[x**2 for x in py_list]
end=time.time()
print(f"python list total time ={end-start} seconds")

np_array=np.array(py_list)
start=time.time()
sq_arr=np_array**2
end=time.time()
print(f"NumPy array total time ={end-start} seconds")

python list total time =0.10355734825134277 seconds
NumPy array total time =0.002138376235961914 seconds


In [9]:
import sys
print(f"Python list size={sys.getsizeof(py_list)*len(py_list)}bytes")
print(f"NumPy array size={np_array.nbytes} bytes")

Python list size=8448728000000bytes
NumPy array size=8000000 bytes


In [12]:
#create from list
arr=np.array([1,2,3,4,5,6])
print(arr,arr.dtype,arr.shape)

[1 2 3 4 5 6] int64 (6,)


In [11]:
#convert all in one data type..........
arr2=np.array([1,2,3,4,5,"Ankit"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

['1' '2' '3' '4' '5' 'Ankit'] <class 'numpy.ndarray'> <U21 (6,)


In [14]:
#creating 2d array using list.........
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [31]:
#create using built-in functions
arr1=np.zeros((2,3),int) #prefill
print(arr1,arr1.shape)
arr2=np.ones((2,3),int) #prefill
print(arr2,arr2.shape)
arr3=np.full((2,3),5) #prrefill with values
print(arr3,arr3.shape)
arr4=np.eye((5))     #identity matrix
print(arr4,arr4.shape)
arr5=np.arange(1,11,2) # range element
print(arr5,arr5.shape)
arr6=np.linspace(1,100,4) #evenly spaced arrays
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] (5, 5)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [42]:
arr=np.array([[1,2,3],[4,5,6]])

print(arr.shape)  #dimensions= m x n
print(arr.size)   #total elements -5
print(arr.dtype)  #type of elements
print(arr.ndim)   # no of dimention
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(2, 3)
6
int64
2
[[1. 2. 3.]
 [4. 5. 6.]] float64


In [45]:
#operations on numpy array 
#Reshape
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened=arr.flatten()  # 2d to 1d
print(flattened,flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [58]:
#indexing
# arr=np.array([1,2,3])
# print(arr[0])
# print(arr[2])


#2D indexing

arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,0])

#fancy indexing

arr=np.array([1,2,3,4,5,6])
idx=[0,5,2]
print(arr[idx])

# boolean indexing
arr=np.array([1,2,3,4,5,6])
print(arr[arr>3])
print(arr[arr%2==1])
print(arr[arr%2==0])

4
[1 6 3]
[4 5 6]
[1 3 5]
[2 4 6]


In [59]:
#slicing
arr=np.array([1,2,3,4,5,6])
print(arr[1:4])
print(arr[:4])
print(arr[:])
print(arr[1:4:2])


[2 3 4]
[1 2 3 4]
[1 2 3 4 5 6]
[2 4]


In [61]:
#copy vs view
ls=[1,2,3,4,5]
sub_ls=ls[1:4]
sub_ls[0]=200
print(sub_ls)
print(ls)

arr=np.array([1,2,3,4,5])
sub_arr=arr[1:4]
sub_arr[0]=200
print(sub_arr)
print(arr)

[200, 3, 4]
[1, 2, 3, 4, 5]
[200   3   4]
[  1 200   3   4   5]


In [68]:
#data type
#int type int32,int64
arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)
arr=np.array([1,2.0,3,4,5])
print(arr,arr.dtype)

#complex data type
arr1=np.array([5+8j])
print(arr1,arr1.dtype)
arr2=np.array([2+5j])
print(arr2,arr2.dtype)
print(arr1+arr2)
print(arr1-arr2)

#string data type
arr=np.array(["Ankit","Yadav",231])
print(arr,arr.dtype)

#object data type
arr=np.array(["Ankit","Yadav",{1,2,3},8.56])
print(arr,arr.dtype)

[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64
[5.+8.j] complex128
[2.+5.j] complex128
[7.+13.j]
[3.+3.j]
['Ankit' 'Yadav' '231'] <U21
['Ankit' 'Yadav' {1, 2, 3} 8.56] object


In [74]:
#multi dimensions array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(np.sum(arr))
sum_of_cols=np.sum(arr,axis=0)
print(sum_of_cols)
sum_of_rows=np.sum(arr,axis=1)
print(sum_of_rows)
print(arr[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [84]:
# 3d Array
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D,arr3D.shape)
#indexing
print(arr3D[1,2,1])
# slicing
print(arr3D[:,1,:]) #second row from both layers
print(arr3D[:,1:,0])# access 0th column 1st and 2nd elements
arr3D[:,0,:]=99      #change value from indexes
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
12
[[ 3  4]
 [ 9 10]]
[[ 3  5]
 [ 9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [87]:
#Vectorization
arr1=np.array([1,2,3,4,5])
arr2=np.array([11,12,13,14,15])
print(arr1**2)
print(arr1+arr2)
print(arr1+1)

[ 1  4  9 16 25]
[12 14 16 18 20]
[2 3 4 5 6]


In [92]:
#broadcasting
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1.shape)
print(arr2.shape)
print(arr1+arr2)


(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [95]:
#vector Noramalisation
arr=np.array([[1,2],[3,4]])
mean =np.mean(arr)
print(f"Mean is :{np.mean(arr)}")
std_dev=np.std(arr)
print(f"SD is :{np.std(arr)}")
normalised_arr=(arr-mean)/std_dev
print(normalised_arr)

Mean is :2.5
SD is :1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [100]:
# Mathematical fnx
# Aggregation
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.max(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
0
5
4
3.0
1.4142135623730951
3.0
2.0


In [101]:
# power fnx
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [104]:
# log fnx
arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [105]:
# rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [108]:
#unique
arr=np.array([1,2,2,-4,5])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))  #if number are in negetive then it is convert them to positive 

[-4  1  2  5]
[-4  1  2  2  5]
[1 2 2 4 5]
